### ISSUE TITLE
python2-config doesn't exist on macports

### ISSUE THREAD

**Issue by coke** [niner/Inline-Python#15]
I was having trouble installing Inline::Python on a fresh perl 6 install on my mac.

Tracked it down to a missing python2-config.

I DO, however, have a specific variant of this:

/opt/local/bin/python2.7-config

When I copied that to python2-config, I was able to install without a problem.

Might want to try both of those config scripts before giving up.

**Comment by niner** [comment]
Fixed by commit e925a7def0
