### ISSUE TITLE
Using matplotlib.pyplot segfaults

### ISSUE THREAD

**Issue by moritz** [niner/Inline-Python#17]
This is Rakudo version 2017.02 built on MoarVM version 2017.02
    implementing Perl 6.c.
    
This code:

    use v6;
    use Inline::Python;

    use matplotlib::pyplot:from<Python>;

reliably segfaults. This is what it looks like in the debugger:

    $ perl6-gdb-m plot.p6
    ================================================================================================
    This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2017.02 built on MoarVM version 2017.02,
    running on ubuntu (16.04.2.LTS.Xenial.Xerus) / linux (4.4.0.62.generic)
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/moritz/p6/rakudo/install/bin/moar...(no debugging symbols found)...done.
    Starting program: /home/moritz/p6/rakudo/install/bin/moar --execname=/home/moritz/bin/perl6-gdb-m --libpath=/home/moritz/p6/rakudo/install/share/nqp/lib --libpath=/home/moritz/p6/rakudo/install/share/perl6/lib --libpath=/home/moritz/p6/rakudo/install/share/perl6/runtime /home/moritz/p6/rakudo/install/share/perl6/runtime/perl6.moarvm plot.p6
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    
    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff453c070 in PyObject_GetAttrString ()
       from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
    (gdb) bt
    #0  0x00007ffff453c070 in PyObject_GetAttrString ()
       from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
    #1  0x00007ffff78a3630 in dcCall_x64_sysv ()
       from //home/moritz/p6/rakudo/install/lib/libmoar.so
    #2  0x00000000006037c0 in ?? ()
    #3  0x00007fffffffd490 in ?? ()
    #4  0x00007ffff78a3569 in dc_callvm_call_x64 ()
       from //home/moritz/p6/rakudo/install/lib/libmoar.so
    Backtrace stopped: previous frame inner to this frame (corrupt stack?)
    (gdb) 

Importing the same module in python itself does not segfault.

**Comment by niner** [comment]
Fixed in commit 7c3d51bfcb.
Thanks for the report!

**Comment by moritz** [comment]
Thanks for the quick fix, @niner. I can confirm that the segfault is gone now.
