### ISSUE TITLE
Installation via panda does not edit Makefile sufficiently

### ISSUE THREAD

**Issue by avuserow** [niner/Inline-Python#2]
It appears that configure.pl6's logic for adding the Python specific details to the Makefile does not happen when running under Panda. As far as I can tell, panda runs the logic in Build.pm, which doesn't do all the right stuff.

If I manually run configure.pl6, it builds correctly. (But there's no install target in the Makefile, as claimed in the README.)

**Comment by niner** [comment]
Fixed in commit 327148b3c125ab8b70ecba8d7f756b0a4adc0385
Thanks for the report!
