### ISSUE TITLE
Test failure on linux (latest rakudo)

### ISSUE THREAD

**Issue by moritz** [niner/Inline-Python#3]
This is what I get on a debian testing box:

    rakudobrew@hack:~$ panda install Inline::Python
    ==> Fetching Inline::Python
    ==> Building Inline::Python
    gcc pyhelper.c -Wall -I"/usr/include/python2.7" -L"/usr/lib/python2.7/config-x86_64-linux-gnu" -lpython2.7 -shared -o /home/rakudobrew/.panda-work/1424369897_1/blib/lib/Inline/pyhelper.so -fPIC -g
    Compiling lib/Inline/Python.pm6 to mbc
    ==> Testing Inline::Python
    t/call.t ................ ok  
    t/call_back.t ........... ok
    t/callables.t ........... ok
    t/eval.t ................ ok
    t/eval_return_values.t .. ok
    WARNING:root:foo
    t/exceptions.t .......... ok
    Too few positionals passed; expected 2 arguments but got 1
      in method invoke at lib/Inline/Python.pm6:488
      in block <unit> at t/inherit.t:63
    # Looks like you planned 8 tests, but ran 4
    t/inherit.t ............. 
    Dubious, test returned 255 (wstat 65280, 0xff00)
    Failed 4/8 subtests 
    t/invoke.t .............. ok
    t/p6_to_py.t ............ ok
    t/precomp.t ............. ok
    t/py_to_p6.t ............ ok
    Test Summary Report
    -------------------
    t/inherit.t           (Wstat: 65280 Tests: 4 Failed: 0)
      Non-zero exit status: 255
      Parse errors: Bad plan.  You planned 8 tests but ran 4.
    Files=11, Tests=370, 10 wallclock secs ( 0.08 usr  0.02 sys +  8.74 cusr  0.49 csys =  9.33 CPU)
    Result: FAIL
    test stage failed for Inline::Python: Tests failed
      in method install at lib/Panda.pm:124
      in method resolve at lib/Panda.pm:194
      in sub MAIN at /home/rakudobrew/rakudobrew/bin/../moar-nom/install/languages/perl6/site/bin/panda:20
      in sub MAIN at /home/rakudobrew/rakudobrew/bin/../moar-nom/install/languages/perl6/site/bin/panda:18
      in block <unit> at /home/rakudobrew/rakudobrew/bin/../moar-nom/install/languages/perl6/site/bin/panda:77
    
    
    Failure Summary
    sal 1 + 2 * 3 !! 4;
    ----------------
    Inline::Python
            *test stage failed for Inline::Python: Tests failed
    rakudobrew@hack:~$ perl6-m --version
    This is perl6 version 2015.01-223-g313ea7b built on MoarVM version 2015.01-72-g9106bee
    
If you need a shell account on the box to be able to reproduce, this could be arranged.

**Comment by niner** [comment]
Fixed in commit 892f400eb022215f44be89904b6a192226a35763

Thanks for the report!
