### ISSUE TITLE
Must use force-test on 2022.02

### ISSUE THREAD

**Issue by p6steve** [niner/Inline-Python#43]
Welcome to Rakudo™ v2022.02.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.02. 

zef install -v Inline::Python --exclude="python3"
===> Searching for: Inline::Python
===> Found: Inline::Python:ver<0.5>:auth<cpan:NINE> [via Zef::Repository::Ecosystems<cpan>]
===> Searching for missing dependencies: Distribution::Builder::MakeFromJSON
===> Found dependencies: Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner> [via Zef::Repository::Ecosystems<p6c>]
===> Searching for missing dependencies: System::Query
===> Found dependencies: System::Query:ver<0.1.6>:auth<zef:tony-o> [via Zef::Repository::Ecosystems<fez>]
===> Fetching [OK]: Inline::Python:ver<0.5>:auth<cpan:NINE> to /home/jovyan/.zef/tmp/1645567039.36.3224.4820168575948/Inline-Python-0.5.tar.gz
===> Fetching [OK]: Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner> to /home/jovyan/.zef/tmp/1645567039.36.4667.442235647112/Distribution-Builder-MakeFromJSON.git
===> Fetching [OK]: System::Query:ver<0.1.6>:auth<zef:tony-o> to /home/jovyan/.zef/tmp/1645567039.36.4168.748184738817/d254fdd0efd10a06bde98ee99b6ab1349532760a.tar.gz
===> Extraction [OK]: Inline::Python to /home/jovyan/.zef/tmp/Inline-Python-0.5.tar.gz
===> Extraction [OK]: Distribution::Builder::MakeFromJSON to /home/jovyan/.zef/tmp/Distribution-Builder-MakeFromJSON.git
===> Extraction [OK]: System::Query to /home/jovyan/.zef/tmp/d254fdd0efd10a06bde98ee99b6ab1349532760a.tar.gz
===> Building: Inline::Python:ver<0.5>:auth<cpan:NINE>
[Inline::Python] Command: /usr/bin/rakudo -I/home/jovyan/.zef/tmp/Distribution-Builder-MakeFromJSON.git/db586206d7c4d62a4d5033be3a23e42b1e0e48a2 -I/home/jovyan/.zef/tmp/d254fdd0efd10a06bde98ee99b6ab1349532760a.tar.gz -MMONKEY-SEE-NO-EVAL -e exit((require ::(q|Distribution::Builder::MakeFromJSON|)).new(:meta(EVAL($*IN.slurp(:close)))).build(q|/home/jovyan/.zef/tmp/Inline-Python-0.5.tar.gz/Inline-Python-0.5|)??0!!1)
[Inline::Python] gcc pyhelper.c -I/opt/conda/include/python3.9 -I/opt/conda/include/python3.9  -Wno-unused-result -Wsign-compare -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem /opt/conda/include -fdebug-prefix-map=/drone/src/build_artifacts/python-split_1633877476963/work=/usr/local/src/conda/python-3.9.7 -fdebug-prefix-map=/opt/conda=/usr/local/src/conda-prefix -DNDEBUG -fwrapv -O3 -Wall -L/opt/conda/lib/python3.9/config-3.9-aarch64-linux-gnu -L/opt/conda/lib -lpython3.9 -lcrypt -lpthread -ldl  -lutil -lm -lm  -shared -fPIC -o resources/libraries/libpyhelper.so
[Inline::Python] pyhelper.c: In function ‘py_string_as_string’:
[Inline::Python] pyhelper.c:146:12: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
[Inline::Python]   146 |     return PyUnicode_AsUTF8(obj);
[Inline::Python]       |            ^~~~~~~~~~~~~~~~~~~~~
[Inline::Python] pyhelper.c: In function ‘py_raise_missing_method’:
[Inline::Python] pyhelper.c:262:30: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
[Inline::Python]   262 |         char *c_class_name = PyUnicode_AsUTF8(class_name);
[Inline::Python]       |                              ^~~~~~~~~~~~~~~~
[Inline::Python] pyhelper.c: In function ‘perl6_invoke’:
[Inline::Python] pyhelper.c:362:18: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
[Inline::Python]   362 |     char * buf = PyUnicode_AsUTF8AndSize(name, &length);
[Inline::Python]       |                  ^~~~~~~~~~~~~~~~~~~~~~~
[Inline::Python] pyhelper.c: In function ‘py_call_method’:
[Inline::Python] pyhelper.c:323:12: warning: ‘py_retval’ may be used uninitialized in this function [-Wmaybe-uninitialized]
[Inline::Python]   323 |     return py_retval;
[Inline::Python]       |            ^~~~~~~~~
===> Building [OK] for Inline::Python:ver<0.5>:auth<cpan:NINE>
===> Testing: System::Query:ver<0.1.6>:auth<zef:tony-o>
[System::Query] t/array.t .. ok
[System::Query] t/basic.t .. ok
[System::Query] t/die.t .... ok
[System::Query] t/env.t .... ok
[System::Query] t/one.t .... ok
[System::Query] All tests successful.
[System::Query] Files=5, Tests=13,  1 wallclock secs
[System::Query] Result: PASS
===> Testing [OK] for System::Query:ver<0.1.6>:auth<zef:tony-o>
===> Testing: Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
[Distribution::Builder::MakeFromJSON] t/01-basic.t .. ok
[Distribution::Builder::MakeFromJSON] All tests successful.
[Distribution::Builder::MakeFromJSON] Files=1, Tests=1,  0 wallclock secs
[Distribution::Builder::MakeFromJSON] Result: PASS
===> Testing [OK] for Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
===> Testing: Inline::Python:ver<0.5>:auth<cpan:NINE>
[Inline::Python] t/call.t ................ ok
[Inline::Python] t/call_back.t ........... ok
[Inline::Python] t/callables.t ........... ok
[Inline::Python] t/date.t ................ ok
[Inline::Python] t/eval.t ................ ok
[Inline::Python] t/eval_return_values.t .. ok
[Inline::Python] t/exceptions.t .......... ok
[Inline::Python] t/import.t .............. ok
[Inline::Python] t/inherit.t ............. ok
[Inline::Python] t/invoke.t .............. ok
[Inline::Python] t/matplotlib.t .......... ok
[Inline::Python] t/p6_to_py.t ............ Dubious, test returned 255
[Inline::Python] All 12 subtests passed 
[Inline::Python] t/py_to_p6.t ............ Dubious, test returned 1
[Inline::Python] All 10 subtests passed 
[Inline::Python] All tests successful.
[Inline::Python] 
[Inline::Python] Test Summary Report
[Inline::Python] -------------------
[Inline::Python] t/p6_to_py.t  (Wstat: 65280 Tests: 1 Failed: 0)
[Inline::Python] Non-zero exit status: 255
[Inline::Python]   Parse errors: Bad plan.  You planned 12 tests but ran 1.
[Inline::Python] t/py_to_p6.t  (Wstat: 256 Tests: 10 Failed: 0)
[Inline::Python] Non-zero exit status: 1
[Inline::Python]   Parse errors: No plan found in TAP output
[Inline::Python] Files=13, Tests=370,  6 wallclock secs
[Inline::Python] Result: FAILED
===> Testing [FAIL]: Inline::Python:ver<0.5>:auth<cpan:NINE>
Aborting due to test failure: Inline::Python:ver<0.5>:auth<cpan:NINE> (use --force-test to override)

**Comment by p6steve** [comment]
Digging in a bit, the p6_to_py.t error msg is on value ```Buf.new(228,98,99)``` throws 'This container does not reference a native unsigned integer'

I naively expect that this error is thrown by the PyObject lib on CallObject and may have something to do with the UniCode representation of this object having changed between 2021.05 (works) and 2022.02 (fails)

**Comment by p6steve** [comment]
this is python 3.9.7 on ubuntu

**Comment by niner** [comment]
Fixed in https://github.com/niner/Inline-Python/commit/05806b0aee2ded79391b63ee5537b7277d17a6b6
Rakudo is a bit more picky now about signed vs. unsigned native ints.

**Comment by librasteve** [comment]
thanks!
