### ISSUE TITLE
`import.t` Could not find Precomp 

### ISSUE THREAD

**Issue by librasteve** [niner/Inline-Python#48]
t/import.t .............. ===SORRY!=== Error while compiling /home/jovyan/Inline-Python/t/import.t
Could not find Precomp in:
    /home/jovyan/Inline-Python/lib
    /home/jovyan/.raku
    /home/jovyan/rakudo/share/perl6/site
    /home/jovyan/rakudo/share/perl6/vendor
    /home/jovyan/rakudo/share/perl6/core
    CompUnit::Repository::AbsolutePath<3021434752000>
    CompUnit::Repository::NQP<3021434526280>
    CompUnit::Repository::Perl5<3021434526320>
at /home/jovyan/Inline-Python/t/import.t:6
t/import.t .............. Dubious, test returned 1 (wstat 256, 0x100)
No subtests run

**Comment by niner** [comment]
The error message looks quite odd given that on line 4 in that test file we do `use lib 't/lib';`
Even if we're in an unexpected working directory and thus the relative path points at the wrong location, t/lib should at least appear in the list of paths searched in the error message.

**Comment by librasteve** [comment]
You are correct, this is a non-issue
