### ISSUE TITLE
name 'capwords' is not defined

### ISSUE THREAD

**Issue by librasteve** [niner/Inline-Python#49]
When could not find Precomp fixed, then getting a real issue:

```
(base) root@3e1dd9b36003:~/Inline-Python/t# raku import.t 
name 'capwords' is not defined
  in method call at /home/jovyan/rakudo/share/perl6/site/sources/37653EDB728A26F20B16AF45FDA81F139277FD9B (Inline::Python) line 373
  in sub  at /home/jovyan/rakudo/share/perl6/site/sources/37653EDB728A26F20B16AF45FDA81F139277FD9B (Inline::Python) line 428
  in block <unit> at import.t line 11
```

`t/lib/Precomp.pm6` is definitely being used.

**Comment by niner** [comment]
It's not something like that function just being removed. It's still there from Python 2 https://docs.python.org/2/library/string.html#string.capwords to the very latest Python 3 version: https://docs.python.org/3/library/string.html#string.capwords

**Comment by librasteve** [comment]
yes, I checked that it runs fine in my Python ;-)

so it's something to do with the way that the `string::capword` raku symbol is being loaded afaict

I am not clear on what the purpose of separating Precomp.pm, in the commit description is says:

```
Fix "Representation must be composed before it can be serialized"
Modules using Inline::Python may not be precompiled as the Python
interpreter's state cannot be saved/restored.
```

Is it possible that we need some other way to stop precomp (ie that this behaviour has changed in recent raku)?

**Comment by niner** [comment]
When you runn the test with RAKUDO_MODULE_DEBUG=1 you should see whether it's prompting that module. But it's quite unlikely

**Comment by librasteve** [comment]
You are correct - this is a non-issue - closing now
