### ISSUE TITLE
fails to install through panda

### ISSUE THREAD

**Issue by Zhtwn** [niner/Inline-Python#5]
Running "panda install Inline::Python" gives:

```
==> Testing Inline::Python
t/call.t ................ ok
t/call_back.t ........... ok
===SORRY!===
No such method 'py_dec_ref' for invocant of type 'Inline::Python'
t/callables.t ........... 
```
However, if I clone Inline::Python from github on the same platform, "make test" succeeds, and using "panda look" and then "make test" also succeeds.

I'm using Linux Mint Debian edition, with python 2.7.9

labster tried it on OS X -- with python 2.7.6, the panda install succeeded; after installing python 2.7.9 with homebrew, it gave the same failure, but after uninstalling 2.7.9 it still gives the same failure.

**Comment by niner** [comment]
Fixed in commit ad9c980

Thanks for reporting!
