### ISSUE TITLE
Call using eval?

### ISSUE THREAD

**Issue by awwaiid** [niner/Inline-Python#7]
Any chance this can work the same way Inline::Perl5 works?

    EVAL("1", :from<Python>)

**Comment by niner** [comment]
Oh, yes, definitely. There are lots of Inline::Perl5 features, that could be easily ported. My strategy is just to "finish" Inline::Perl5 first, so I actually know what the whole API should look like and not have to go back and forth with Inline::Python, too. But exporting an EVAL multi candidate is rather straight forward.

**Comment by awwaiid** [comment]
Yep. Added in #8 . I also started Inline::Ruby. I'm thinking maybe we need an Inline::Language or some base class that we can put shared code into.
